language: r
cache: packages
r:
  - oldrel
  - release
  - devel
  
before_install:
  - tlmgr install index
  
install:
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz
